[phases.setup]
nixPkgs = ["deno", "playwright-driver"]

[phases.install]
cmds = ["deno install --allow-scripts=npm:playwright npm:playwright"]

[start]
cmd = "deno run --allow-net --allow-read --allow-env --allow-write --allow-run --allow-sys scraper.ts"
